export const themes = {
  morning: {
    bg: 'bg-gradient-to-br from-amber-50 via-orange-50 to-yellow-100',
    cardBg: 'bg-white/70 backdrop-blur-md',
    text: 'text-amber-900',
    subtext: 'text-amber-700',
    accent: 'text-orange-500',
    border: 'border-amber-200/50',
    icon: 'text-orange-400',
    badge: 'bg-amber-100 text-amber-800',
  },
  late_morning: {
    bg: 'bg-gradient-to-br from-sky-50 via-blue-50 to-cyan-50',
    cardBg: 'bg-white/70 backdrop-blur-md',
    text: 'text-sky-900',
    subtext: 'text-sky-700',
    accent: 'text-blue-500',
    border: 'border-sky-200/50',
    icon: 'text-blue-400',
    badge: 'bg-sky-100 text-sky-800',
  },
  afternoon: {
    bg: 'bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50',
    cardBg: 'bg-white/80 backdrop-blur-md',
    text: 'text-slate-900',
    subtext: 'text-slate-600',
    accent: 'text-blue-600',
    border: 'border-slate-200/50',
    icon: 'text-indigo-400',
    badge: 'bg-blue-100 text-blue-800',
  },
  evening: {
    bg: 'bg-gradient-to-br from-slate-900 via-purple-900 to-indigo-950',
    cardBg: 'bg-white/10 backdrop-blur-lg',
    text: 'text-slate-100',
    subtext: 'text-slate-300',
    accent: 'text-purple-400',
    border: 'border-white/10',
    icon: 'text-purple-300',
    badge: 'bg-purple-900/50 text-purple-200',
  },
  idle: {
    bg: 'bg-gradient-to-br from-gray-900 via-slate-900 to-zinc-900',
    cardBg: 'bg-white/5 backdrop-blur-lg',
    text: 'text-gray-200',
    subtext: 'text-gray-400',
    accent: 'text-emerald-400',
    border: 'border-white/5',
    icon: 'text-emerald-300',
    badge: 'bg-gray-800 text-gray-300',
  },
};
